export const presentationContent = {
  meta: {
    title: "Төгсөлтийн өдөр",
    subtitle: "Kami ",
    kicker: "9-13 насны сурагчдын beginner Python аялал",
    date: "Graduation Day",
    organization: "Кодын анги",
  },
  slides: [
    {
      type: "welcome",
      eyebrow: "Kami төгсөлт",
      title: "Төгсөлтийн хичээл",
      lead: "Код бичиж, бодлоо алгоритм болгосон сурагчдаа баяр хүргэе.",
      badges: [
        "Python анхан шат",
        "Алгоритмын үндсэн ойлголт",
        "Компьютерийн суурь мэдлэг",
      ],
      codeLines: ["move_forward()", "turn_right()", "collect()", "build()"],
    },
    {
      type: "about",
      eyebrow: "erxes academy",
      title: "Kami хөтөлбөр гэж юу вэ?",
      lead: "Програмчлалын их ертөнцөд хөл тавьсан эхний алхам юм.",
      points: [
        "Алгоритмын суурь ойлголтууд",
        "Компьютерийн суурь мэдлэг",
        "Анхан шатны Python код бичих чадвар",
      ],
      placeholderTitle: "Kami  зураг",
      placeholderText: "Энд тоглоомын screenshot эсвэл class image байрлуулна",
    },
    {
      type: "platform",
      eyebrow: "Сургалтын платформ",
      title: "Codingforkids.io платформ",
      lead: "Олон улсын жишигт нийцсэн сургалтын орчин:",
      points: [
        {
          text: "Хүүхдийн сонирхлыг татах интерактив тоглоом",
          icon: "Gamepad2",
        },
        {
          text: "Алгоритмын суурь ойлголтууд",
          icon: "Binary",
        },
        {
          text: "Python код бичих анхан шатны мэдлэг",
          icon: "Code2",
        },
        {
          text: "Олон улсын стандартын шаардлагыг хангасан хөтөлбөр",
          icon: "Globe",
          subpoints: [
            "Computer Science Teachers Association (CSTA)",
            "International Society for Technology in Education (ISTE)",
            "K-12 Computer Science Framework",
          ],
        },
      ],
      placeholderTitle: "Codingforkids зураг",
      placeholderText: "Энд тоглоомын screenshot эсвэл class image байрлуулна",
    },
    {
      type: "learning",
      eyebrow: "Суралцсан эрдэм",
      title: "Сурагчид юу сурсан бэ?",
      lead: "2 сар || 16 удаагийн оролт || 8 том сэдэв || 1000+ мөр код.",
      steps: [
        {
          label: "Хувьсагч",
          text: "Мэдээллийг хадгалах",
          icon: "Variable",
        },
        {
          label: "Операторууд",
          text: "Тооцоолол хийх",
          icon: "Calculator",
        },
        {
          label: "Давталт",
          text: "Үйлдлийг давтах",
          icon: "Repeat",
        },
        {
          label: "List",
          text: "Мэдээллийг жагсаах",
          icon: "List",
        },
        {
          label: "Нөхцөл",
          text: "Шийдвэр гаргах",
          icon: "Split",
        },
        {
          label: "Функц",
          text: "Кодоо багцлах",
          icon: "Box",
        },
        {
          label: "Dictionary",
          text: "Түлхүүр үгээр хадгалах",
          icon: "Book",
        },
        {
          label: "Class & Object",
          text: "Объект хандлага",
          icon: "Shapes",
        },
        {
          label: "Техник хангамж",
          text: "Компьютерийн бүтэц",
          icon: "Cpu",
        },
        {
          label: "Дижитал соёл",
          text: "Зөв хэрэглээ",
          icon: "ShieldCheck",
        },
      ],
    },
    {
      type: "topics",
      eyebrow: "Дадал ба Сэтгэлгээ",
      title: "Кодоос гадна юу сурав?",
      lead: "Програмчлал бол зөвхөн код бичих биш, асуудал шийдэх урлаг юм.",
      topics: [
        {
          title: "Логик сэтгэлгээ",
          text: "Асуудлыг алхам алхмаар задлах",
          icon: "Brain",
        },
        {
          title: "Тэвчээр",
          text: "Алдаанаас буцахгүй турших",
          icon: "Hourglass",
        },
        {
          title: "Бүтээлч байдал",
          text: "Өөрийн санааг код болгох",
          icon: "Lightbulb",
        },
        {
          title: "Debugging",
          text: "Алдааг хайж олох, засах",
          icon: "Bug",
        },
        {
          title: "Problem Solving",
          text: "Асуудлыг жижиглэж шийдэх",
          icon: "Puzzle",
        },
        {
          title: "Харилцаа холбоо",
          text: "Өөрийн кодоо бусдад тайлбарлах",
          icon: "MessagesSquare",
        },
      ],
    },
    {
      type: "skills",
      eyebrow: "Roadmap: 0-оос Hero руу",
      title: "Сурагчдын ахиц",
      lead: "2 сарын хугацаанд туулсан зам.",
      milestones: [
        {
          label: "Эхлэл",
          title: "0-ээс эхлэв",
          text: "Компьютерийн анхан шатны ойлголтуудтай танилцсан",
          icon: "CircleQuestionMark",
        },
        {
          label: "Дунд үе",
          title: "Анхны код",
          text: "Програмчлалын ертөнцөд тавьсан анхны алхам",
          icon: "Binary",
        },
        {
          label: "Дунд үе",
          title: "Програмчлал",
          text: "Алгоритмын суурь ойлголтуудыг эзэмшсэн",
          icon: "Layers",
        },
        {
          label: "Төгсгөл",
          title: "Бие даах",
          text: "Нарийн төвөгтэй код бичиж, асуудлыг бие даан шийддэг болсон",
          icon: "Rocket",
        },
      ],
    },
    {
      type: "compare",
      eyebrow: "Ахиц дэвшил",
      title: "Эхний ба сүүлийн код",
      lead: "2 сарын хугацаанд сурагчдын бичсэн кодын хөгжил болон бүтээсэн тоглоом.",
      first: {
        title: "Эхний хичээлийн код",
        icon: "Code",
        codeLines: [
          "import player",
          "",
          "player.move_forward()",
          "player.move_forward()",
          "player.move_forward()",
        ],
        imageSrc: "/first.png",
        imageAlt: "Эхний хичээлийн зураг",
        placeholderTitle: "Анхны зураг",
        placeholderText:
          "Энд анхны хичээлийн тоглоом эсвэл кодын үр дүнгийн зургийг оруулаарай.",
      },
      last: {
        title: "Төгсгөлийн төслийн код",
        icon: "Sparkles",
        codeLines: [
          "import player",
          "",
          "# Grab the bag of seeds and head to the light X mark",
          "",
          "# Collect water using collect() function",
          "",
          "def sow_field(tree, loops, direction):",
          "    for x in range(loops):",
          "        if direction == 'right':",
          "            player.move_forward(2)",
          "            player.turn_left()",
          "            player.plant(seeds, tree)",
          "            player.water()",
          "            player.turn_right()",
          "            player.move_forward()",
          "        if direction == 'left':",
          "            player.move_forward()",
          "            player.turn_right()",
          "            player.plant(seeds, tree)",
          "            player.water()",
          "            player.turn_left()",
          "            player.move_forward(2)",
          "",
          "# Head for the top of the map and use custom function",
          "",
          "player.turn_left()",
          "player.turn_left()",
          "player.move_forward(7)",
          "player.turn_left()",
          "player.collect('water')",
          "player.turn_right()",
          "player.move_forward(3)",
          "player.turn_right()",
          "sow_field('orange', 3, 'right')",
          "player.move_forward(3)",
          "player.turn_right()",
          "player.move_forward(3)",
          "player.turn_right()",
          "sow_field('pear', 4, 'left')",
          "player.turn_left()",
          "player.move_forward(3)",
          "player.turn_left()",
          "player.move_forward(3)",
          "sow_field('apple', 3, 'right')",
          "",
          "player.turn_right()",
          "player.move_forward(3)",
          "player.turn_right()",
          "player.move_forward(3)",
          "sow_field('peach', 2, 'left')",
        ],
        imageSrc: "/last.png",
        imageAlt: "Төгсгөлийн төслийн зураг",
        placeholderTitle: "Сүүлчийн зураг",
        placeholderText:
          "Энд сүүлийн хичээлийн төсөл, тоглоомын зураг эсвэл ангийн зургийг оруулаарай.",
      },
    },
    {
      type: "parents",
      eyebrow: "Эцэг эх, асран хамгаалагчдад",
      title: "Баярлалаа",
      lead: "Хүүхдийнхээ ирээдүйд хөрөнгө оруулалт хийж, тэднийг дэмжсэнд.",
      supportPoints: [
        "Төсөл дээр нь хамт ажиллаж, сонирхож асуух",
        "Алдаа гаргах үед нь урамшуулж, турших боломж олгох",
        "Сургалтын дараах бие даах цагийг нь дэмжих",
      ],
      testimonials: [
        {
          author: "Рита Пиерсон, TED Talk “Every Kid Needs a Champion”",
          text: "Хүүхэд бүрт түүнийг орхихгүй, холбоо харилцааны хүчийг ойлгодог, боломжид нь итгэдэг нэгэн насанд хүрсэн хүн хэрэгтэй.",
        },
      ],
    },
    {
      type: "achievement",
      eyebrow: "Хичээл зүтгэлийн баталгаа",
      title: "Сурагчдын амжилтын гэрчилгээ",
      lead: "Өнөөдөр тэд анхан шатны Python код бичигч гэсэн эхний том шатандаа хүрлээ.",
      certificateTitle: "Python анхан шатны код бичигч",
      certificateName: "Сурагчийн нэр",
      certificateLine: "Kami сургалт",
      badges: ["Алгоритм сэтгэгч", "Алдаа засагч", "Асуудал шийдвэрлэгч"],
      photoSlots: ["Ангийн зураг", "Сурагчийн ажил", "Төгсөлтийн мөч"],
    },
    {
      type: "kami2",
      eyebrow: "Дараагийн түвшин",
      title: "Kami-2 дээр юу сурах вэ?",
      lead: "Суурь мэдлэгээ бэхжүүлээд зогсохгүй, илүү нарийн төвөгтэй код бичиж өөрсдийн анхны програмыг терминал дээр ажиллуулах чадвартай болох болно.",
      badges: ["Жинхэнэ төслүүд", "IDE", "Чөлөөт код бичих"],
      imageSrc: "/terminal-game.png",
    },
    {
      type: "thanks",
      title: "Амжилттай төгссөн бүх сурагчдадаа баяр хүргэе!",
      lead: "Сурагчдадаа баяр хүргэе. Дараагийн түвшинд дахин уулзацгаая.",
      badges: ["Python", "Бүтээлч байдал", "Өөртөө итгэх итгэл"],
      codeLines: [
        "if student.is_ready:",
        "    open_next_level()",
        "celebrate()",
      ],
    },
  ],
};
